apiVersion: apps/v1
kind: Deployment
metadata:
    name: yeahreally-api
spec:
    selector:
        matchLabels:
            app: yeahreally
    replicas: 2
    template:
        metadata:
            labels:
                app: yeahreally
        spec:
            containers:
            - name: yeahreally
              image: sanjeevmrsoft/yeahreally-apis
              ports:
                - containerPort: 80
---
kind: Service
apiVersion: v1
metadata: 
    name: yeahreally-service
spec:
    selector:
        app: yeahreally
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
    type: NodePort